- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- service_name: "/world/swarm_world/remove"
  ros_type_name: "ros_gz_interfaces/srv/DeleteEntity"
  gz_req_type_name: "gz.msgs.Entity"
  gz_rep_type_name: "gz.msgs.Boolean"

- service_name: "/world/swarm_world/create"
  ros_type_name: "ros_gz_interfaces/srv/SpawnEntity"
  gz_req_type_name: "gz.msgs.EntityFactory"
  gz_rep_type_name: "gz.msgs.Boolean"